modLoader="javafml"
loaderVersion="[47,)"
license="MIT"
[[mods]]
modId="kncrafttentportals"
version="1.0.1"
displayName="KNCraft Tent Portals"
displayTest="IGNORE_SERVER_VERSION"
description="Server-side Nomadic Tents dimension synchronization and immersive entrances."
[[dependencies.kncrafttentportals]]
modId="nomadictents"
mandatory=true
versionRange="[20.1.1,20.1.2)"
ordering="AFTER"
side="SERVER"
[[dependencies.kncrafttentportals]]
modId="immersive_portals"
mandatory=true
versionRange="[3.0.7,3.0.8)"
ordering="AFTER"
side="SERVER"
